import './thumbnail-render.js';
import './create-big-photo.js';
import './upload-form.js';
import './validate.js';
import './photo-scale-editor.js';
import './foto-effects-editor.js';
import './get-data.js';
import './send-formData.js';
import './filters-photo.js';
